### PR TITLE
update to use psr\container

### PR DESCRIPTION
**Pull request by basz**
something 'cs' goes wrong in the tests it seems... Idea?

### CODE REVIEW

**Comment by prolic** [comment]
Can you update the year in license file and all php file headers?

**Comment by prolic** [comment]
The license file in root dir is missing update.

**Comment by prolic** [comment]
Thanks :+1:

**Comment by basz** [comment]
think i got most of the repos... if u see one that I missed let me know

**Comment by prolic** [comment]
Thanks mate. Did you check the new pdo/mongodb snapshot stores?

**Pull request merged**
