### PR TITLE
Implement PSR-15

### LINKED ISSUE #21: Use http-interop for middlewares PSR-15
We should use the [Interop\Http\ServerMiddleware\MiddlewareInterface](https://github.com/php-fig/fig-standards/blob/master/proposed/http-middleware/middleware.md#21-psrhttpservermiddlewaremiddlewareinterface) (PSR-15).

Zend Expressive has a pretty nifty [migration guide](https://docs.zendframework.com/zend-expressive/reference/migration/to-v2/#http-interop).

### PR DESCRIPTION
**Pull request by bgaleotti**
Should close #21

### CODE REVIEW

**Comment by prolic** [comment]
PHP Fatal error:  Call to undefined method ProophTest\Psr7Middleware\CommandMiddlewareTest::expectException() in /home/travis/build/prooph/psr7-middleware/tests/CommandMiddlewareTest.php on line 52

**Comment by prolic** [comment]
@basz @codeliner can you check this please?

**Comment by prolic** [comment]
Php5 is not required to support anymore. Php7.1 only for prooph now.

Am 09.04.2017 01:46 schrieb "Coveralls" <notifications@github.com>:

**Comment by prolic** [comment]
Require service bus v6, prooph common 4.1, phpunit 6

**Comment by prolic** [comment]
PSR container instead of container interop, prooph php-cs-fixer-config, newest interop config from sandrokeil, prooph bookdown template, php 7.1 only. I hope that's it :-)

**Comment by bgaleotti** [comment]
@prolic Didn't realize that most changes are already in `develop`. Opened another MR #24.

**Pull request closed without merging**
